### ISSUE TITLE
9.0

### ISSUE THREAD

**Issue by yelizariev** [codup/odoo-ru#2]
Мы сделали порт под 9.0
https://github.com/odoo-russia/odoo-russia/tree/9.0/addons/l10n_ru

**Comment by yelizariev** [comment]
@wowas18 какие-нибудь комментарии? Есть планы по 9.0?

**Comment by wowas18** [comment]
Привет! Уже то же портировано в 9.0

**Comment by yelizariev** [comment]
Понятно. Где-нибудь опубликовано? 
l10n_ru_doc тоже уже портирован?

**Comment by wowas18** [comment]
https://www.odoo.com/apps/modules/master/l10n_ru/
https://www.odoo.com/apps/modules/master/l10n_ru_doc/
Оба портированы

**Comment by yelizariev** [comment]
:+1:

**Comment by yelizariev** [comment]
Можешь подсказать насчет user_type_id/id
Мы затруднялись с этим и поставили почти наугад account.data_account_type_current_assets, а у тебя account.data_account_type_expenses 
Есть какие-нибудь соображения или это тоже наугад?
