### ISSUE TITLE
В multi-company не применяется план счетов (odoo v9)

### ISSUE THREAD

**Issue by vladletnabov** [codup/odoo-ru#4]
Если используется режим multi-company, то план счетов применяется только для первой(основной) компании, остальные не могут применить с типичной ошибкой:

```
Odoo Warning - Validation Error
The code of the account must be unique per company !
```

Можно SQL запросом в ручную указать нужный план счетови тогда он корректно отображается на странице настроек. Но следствием этого является отсутствие возможности создать контактв дочерней компании:
```
"The following fields are invalid:
- Account Receivable
- Account Payable"
```

**Comment by vladletnabov** [comment]
Та же самая ошибка при указании плана счетов для компании. В логах есть ещё такое:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/skif/odoo/openerp/netsvc.py", line 108, in format
    return DBFormatter.format(self, record)
  File "/home/skif/odoo/openerp/netsvc.py", line 102, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 259: ordinal not in range(128)
Logged from file sql_db.py, line 227
```
Скорее всего используется str(), возможно там необходимо заменить на .encode()

**Comment by wowas18** [comment]
Проверил на последней версии Odoo 9.0
Сейчас должно работать без ошибки

**Comment by vladletnabov** [comment]
К сожалению, ошибка остаётся (использовал последнюю night версию для проверки). Можете сказать, какие модули у вас на стенде включены? Возможно где-то идёт конфликт модулей. Меня вполне устроит удалить лишние и накатить план счетов для филиалов.

**Comment by vladletnabov** [comment]
Сейчас попробовал после обновления ещё раз обновить план счетов: для второй компании план применился, но третья снова даёт ошибку.  и на экране план счетов не применяется.  Останавливаешь сервер. Запускаешь с консоли c ключом обновления модуль плана счетов и он автоматически устанавливается для филиала. Т.е. такаую операцию нужно проводить для каждого филиала. Немного неудобно, но жить можно.
Спасибо.

**Comment by wowas18** [comment]
Странно, у меня такого нет. Хоть для третьей, хоть для четвертой компании без ошибок.
Попробуйте на новой БД. Еще проверьте, что копий модуля нет во всех путях для модулей.
