### ISSUE TITLE
[Odoo 11 CE] Модуль недоступен для установки 

### ISSUE THREAD

**Issue by vostokbike** [codup/odoo-ru#5]
Здравствуйте,
Спасибо за план счетов, пытаюсь поставить на Odoo 11 CE.
Возможно есть идеи как решить проблему?
1. Распаковал архив в папку с модулями, в терминале наблюдаю корректность всех файлов. 
2. Обновляю в гуе оду 11 список модулей, ищу l10n_ru и Russia - Accounting
Модуль не отображается.
В манифесте стоит installable: True. 

Есть какие-то подводные камни с установкой?

**Comment by wowas18** [comment]
Fixed. Please update module.
